### ISSUE TITLE
the organization of the buttons looks stupid.

### ISSUE THREAD

**Issue by SomeGDPerson123** [PetitFrapo/NoMoreGrayFilter#4]
the organization of the buttons looks stupid. i disabled the mod temporarily and can confirm that this mod is causing it.
![image](https://github.com/PetitFrapo/NoMoreGrayFilter/assets/134952617/9732c47e-f166-49da-bdb2-d026de7b78af)
give me my old organization back now

**Comment by PetitFrapo** [comment]
Hello,
I am sorry to say that I have tried to replicate your situation but could not get it that way (I installed my mod as well as SuperExpert), I am confused as this is the first time I see this. My mod takes the original coordinates of the buttons before removing the filter, so it seems weird that it messes them up.
Please provide me with a list of your mods so that I can try to see what went wrong.

**Comment by SomeGDPerson123** [comment]
I will as soon as I get the chance to; I'll show a list for all my mods in a video and show the situation visually

**Comment by PetitFrapo** [comment]
Okay, thanks a lot.

**Comment by SomeGDPerson123** [comment]
https://github.com/PetitFrapo/NoMoreGrayFilter/assets/134952617/0f4742a6-6baf-4252-8ef3-bb85cd2d79e3

**Comment by PetitFrapo** [comment]
Thanks for the video, I have honestly no idea what causes this... This never happened back in 2.204 and I haven't changed the code since, so this really surprises me.

**Comment by immortalbean** [comment]
Seems to be an issue on mobile

**Comment by SomeGDPerson123** [comment]
I was having it on PC when I first issued it, but I can check again

**Comment by PetitFrapo** [comment]
I'm sorry for being slow, but it's finally fixed. I'm waiting for the devs to approve the update, if you're impatient you can download the mod from GitHub and put it in your mods folder

**Comment by SomeGDPerson123** [comment]
Alr, thanks!
